name: van_quiz4_ci_dotnet

trigger:
- main

pool:
  name: Default
  vmImage: "windows-latest"

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: dotnet restore
  displayName: Restore

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: Build

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish App

- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
  displayName: Publish Artifact